# Generated by Django 3.2.3 on 2021-05-31 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('GOD', 'Level God'), ('DRAGON', 'Level Dragon'), ('TIGER', 'Level Tiger'), ('WOLF', 'Level Wolf')], default='WOLF', max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('inBattle', models.BooleanField(default=False)),
                ('battle_duration', models.CharField(max_length=5)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
