# Generated by Django 3.2.3 on 2021-05-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0002_threat_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='battle_duration',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
