# Generated by Django 3.2.3 on 2021-05-31 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
        ('threats', '0003_auto_20210531_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threat',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='threat',
            name='object_id',
        ),
        migrations.AddField(
            model_name='threat',
            name='beaten_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threats', to='heroes.hero'),
        ),
    ]
