# Generated by Django 3.2.3 on 2021-06-02 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0004_auto_20210531_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threat',
            old_name='beaten_by',
            new_name='battle_with',
        ),
    ]
