# Generated by Django 3.2.3 on 2021-06-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0005_rename_beaten_by_threat_battle_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='battle_end_timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='battle_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
