# Generated by Django 3.2.3 on 2021-06-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0006_auto_20210602_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threat',
            old_name='battle_duration',
            new_name='battle_start_timestamp',
        ),
        migrations.AddField(
            model_name='threat',
            name='start_timestamp',
            field=models.IntegerField(blank=True, default=1622677121, null=True),
        ),
    ]
